### ISSUE TITLE
Things Aaron can change

### ISSUE THREAD

**Issue by torch2424** [Kondeo/kondeo-home#2]
I want to change some things about the site, here's whats on the table:

Colors
Remove Yeoman
Add projects/ make them look cooler
Text sizes
Github trackers

Add some cool CSS libraries

**Comment by torch2424** [comment]
in branch aaronChanges

**Comment by julianpoy** [comment]
Aaron is a grown ass man. He can change what he wants.

**Comment by torch2424** [comment]
BWAHAHAHAHAHAHA :'D
